name: Addon Lint

on:
  pull_request:
    paths:
      - .github/workflows/addon-lint.yml
      - 'open_smartcity_home/**'

jobs:
  build:
    name: Add-on configuration
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Checkout
        uses: actions/checkout@v6

      - name: ğŸš€ Run Home Assistant Add-on Lint
        uses: frenck/action-addon-linter@v2
        with:
          path: "./open_smartcity_home"
